<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>El Bule</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../css/main.css">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Great+Vibes" rel="stylesheet">
    <script src="../js/sweetalert.min.js"></script>
    <link rel="stylesheet" href="../css/sweetalert.css">
    
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
  <!-- ***************************
  ************* Logo *************
  ******************************-->
  <div id="logo" class="hidden-xs">
    <div class="container">
      <div class="row">
        <div class="text-logo-1 col-xs-4 hidden-xs">
          <p>"Las mejores hamburguesas de la ciudad de Leon, Gto"</p>
          <p><span>-GourmetMexico.com</span></p>
        </div>
        <div class="col-xs-4">
          <a href="../index.php"><img class="center-block img-responsive" src="../img/logo1.png" width="70%"></a>
        </div>
        <div class="text-logo-2 col-xs-4 hidden-xs">
          <p>"La mejor calidad y el mejor ambiente familiar"</p>
          <p><span>-FastFoodMX.com</span></p>
        </div>
      </div>
    </div>
  </div>