<!-- ***************************
********** Contacto ************
******************************-->
<div id="contacto">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <h1>Ubicación y Contacto</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-md-6">
        <h3>Boulevard Lopez Mateos 77 Col. Esmeralda</h3>
        <h3>Leon Gto. México</h3>
        <h3>1564 725288</h3>
        <h3 class="fa fa-facebook-official"> <span class="fa fa-twitter"></span> <span class="fa fa-instagram"></span> <span class="fa fa-youtube-play"></span></h3><br><br>
        <h3>¡Mantengamos el contacto!</h3>
        <h3>Promociones especiales, eventos y mas.</h3>
        <div class="row">
          <div class="col-xs-12 col-md-8">
            <form>
          <input type="email" name="email" placeholder="Correo Electronico">
          </div>
          <div class="col-xs-12 col-md-4">
            <input class="btn btn-default" type="submit" value="Enviar">
        </form>
          </div>
        </div>
      </div>
      <div class="col-xs-6 hidden-xs hidden-sm">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3721.6698772640275!2d-101.6849433856112!3d21.12572358594589!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x842bbf0d21c1fa9d%3A0xd95de12234cb28ee!2sBoulevard+L%C3%B3pez+Mateos+Poniente%2C+Centro%2C+37000+Le%C3%B3n%2C+Gto.!5e0!3m2!1ses-419!2smx!4v1475296703593" width="500" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
      </div>
    </div>
  </div>
</div>
<div id="mapa-movil" class="visible-xs visible-sm">
  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3721.6698772640275!2d-101.6849433856112!3d21.12572358594589!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x842bbf0d21c1fa9d%3A0xd95de12234cb28ee!2sBoulevard+L%C3%B3pez+Mateos+Poniente%2C+Centro%2C+37000+Le%C3%B3n%2C+Gto.!5e0!3m2!1ses-419!2smx!4v1475296703593" width="100%" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>   
</div>
<!--************************************
* ********** Pie de pagina *************
* ************************************-->
<div id="pie">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <p class="text-center"><span class="pastry">El Bule  </span><span class="glyphicon glyphicon-copyright-mark"> Todos los derechos reservados.</span></p>
      </div>
    </div>
  </div>
</div>
  
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <script src="js/main.js"></script>
    
  </body>
</html>